devices:
- id: Router
  name: Router
  host: 192.168.11.1
  checks:
  - ping
  - snmp
  snmp:
    version: 2c
    community: public
    port: 161
- id: server-app
  name: Server-app
  host: 192.168.11.166
  checks:
  - ping
- id: nas
  name: nas
  host: 192.168.11.224
  checks:
  - ping
- id: simone-pc
  name: simone-pc
  host: 192.168.11.91
  checks:
  - ping
- id: DNS-GOOGLE
  name: DNS-GOOGLE
  host: 1.1.1.1
  checks:
  - ping
- id: PC-marcello-polichem
  name: PC-marcello-polichem
  host: 10.20.10.32
  checks:
  - ping
